spring:
  application:
    name: employee-api

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
      resolve-schema-properties: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    show-actuator: true

server:
  port: 8111

# Resilience4j configuration tuned for mock server behavior
resilience4j:
  retry:
    instances:
      employeeClientRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.RestClientResponseException
          - java.io.IOException
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

  ratelimiter:
    instances:
      employeeClientLimiter:
        limit-for-period: 3
        limit-refresh-period: 1s
        timeout-duration: 500ms

  circuitbreaker:
    instances:
      employeeClientCircuit:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.project.api: DEBUG
    org.springdoc: WARN
    org.springframework.web: INFO